deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A788F8C3CE1342BB8EAD8E9146A5C679 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D3D0BCE31B794D8ABF99C906744C3510 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E6848AF4DF264AA893A5B9AF7677F66D }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'blueApple2022'
          slot-name: 'Production'
          package: '.' # <-- 這就是你需要添加的關鍵行！
