name: snake2022
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Perason to greet'
        required: true
        default: 'World'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: echo Hello ${{ github.event.inputs.name }}!
